apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hellos.foo.com
spec:
  group: foo.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                message:
                  type: string
              allOf:
                - required: ["message"]
  scope: Namespaced
  names:
    plural: hellos
    singular: hello
    kind: Hello
    shortNames:
      - hello
